### ISSUE TITLE
Maximum (20) redirects followed when updating the main bucket

### ISSUE THREAD

**Issue by graphixillusion** [KNOXDEV/knox-scoop#1]
Hi there. As the title says i can't update the main knox-scoop bucket since a few days. This is the log:

Updating 'knox-scoop' bucket...
fatal: unable to access 'https://git.irs.sh/KNOXDEV/knox-scoop/': Maximum (20) redirects followed

It seems a problem related accessing the main domain which is https://git.irs.sh . When i try to open this on a browser i always get: 

"ERR_TOO_MANY_REDIRECTS"

**Comment by KNOXDEV** [comment]
That's embarrassing! Just a Cloudflare bug, thanks! 

Feel free to use the GitHub mirror as your bucket if you want to avoid that in the future.

**Comment by graphixillusion** [comment]
Hi there. Same error again.

**Comment by KNOXDEV** [comment]
As mentioned, just use the github mirror from now on. It's basically the primary source:
```
scoop bucket add https://github.com/KNOXDEV/knox-scoop/
```
